server:
  port: 7000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bl_forum?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: 123456
  cache:
    type: redis
  elasticsearch:
    rest:
      uris: http://localhost:9200
      username: elastic
      password: 123456

# 自定义文件上传路径
web:
  # 访问路径
  path: upload
  # 上传路径
  upload-path: /opt/www/upload
