spring:
  jackson:
    #这个是时区，一定要加，否则会默认为格林尼治时间，即少8小时
    time-zone: GMT+8
    #时间戳统一转换
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: @spring.atcive@

# mybatis-plus 配置
mybatis-plus:
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: cn.bload.forum.model
  # xml
  mapper-locations: classpath:cn/bload/forum/mapper/*.xml

# 是否启用 elsearch
elsearch: true
