server:
  port: 7000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bl_forum?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
  elasticsearch:
    rest:
      uris: http://localhost:9200
      username: elastic
      password: 123456

# 自定义文件上传路径
web:
  # 访问路径
  path: upload
  # 上传路径
  upload-path: E:\临时目录\upload\


mybatis-plus:
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 是否启用 elsearch
elsearch: false
